# Generated by Django 2.1.5 on 2020-11-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='choice',
            new_name='selected_choice',
        ),
    ]
